# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Prometheus 자체 메트릭 수집
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # 쿠버네티스 노드 메트릭 수집
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true  # 보안상 권장되지 않으므로 실제 인증서를 사용하는 것이 좋습니다.
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token  # 추가: 인증을 위한 서비스 어카운트 토큰
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          # __address__ 설정 수정 필요
          - source_labels: [__meta_kubernetes_node_address_InternalIP]  # 수정: 노드의 내부 IP 사용
            target_label: __address__
            replacement: $1:10250  # kubelet 포트로 변경
          - source_labels: [__meta_kubernetes_node_name]
            target_label: instance
            replacement: $1
          # __metrics_path__ 설정 제거 또는 수정
          # kubelet 메트릭 수집 경로로 변경
          - target_label: __metrics_path__
            replacement: /metrics

      # 쿠버네티스 API 서버 메트릭 수집
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  # 추가: CA 인증서 파일 경로
          insecure_skip_verify: true  # 가능하면 false로 설정하고 실제 인증서를 검증하세요.
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token  # 추가: 인증을 위한 서비스 어카운트 토큰
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: kubernetes;https

      # 쿠버네티스 DNS 메트릭 수집
      - job_name: 'kubernetes-coredns'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: kube-dns;metrics

      # 쿠버네티스 kubelet 메트릭 수집
      - job_name: 'kubernetes-kubelet'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true  # 보안상 권장되지 않음
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token  # 추가: 인증을 위한 서비스 어카운트 토큰
        relabel_configs:
          # __address__ 설정 수정 필요
          - source_labels: [__meta_kubernetes_node_address_InternalIP]  # 수정: 노드의 내부 IP 사용
            regex: (.+)
            target_label: __address__
            replacement: $1:10250  # kubelet 포트로 변경
          - source_labels: [__meta_kubernetes_node_name]
            target_label: instance
            replacement: $1

      # Node Exporter 메트릭 수집 (쿠버네티스 서비스 디스커버리 사용)
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: node-exporter
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          # __address__ 설정 확인 필요
          - source_labels: [__meta_kubernetes_pod_ip]
            regex: (.+)
            target_label: __address__
            replacement: $1:9100  # 서비스 디스커버리로 발견된 주소 그대로 사용

      # 쿠버네티스 pod 메트릭 수집
      - job_name: "kubernetes_pods"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
            action: keep
            regex: kube-state-metrics;kube-system
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: /metrics/cadvisor
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            target_label: __address__
            replacement: $1:10250
