#prometheus-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-server
---
#prometheus-PV.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
spec:
  storageClassName: nfs-storage
  claimRef:
    name: prometheus-server-pv-claim
    namespace: prometheus-server
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.1.104
    path: /nfs_shared/prometheus/server
---
#prometheus-PVC.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pv-claim
  namespace: prometheus-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
