- name: Install required packages for container runtime
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  ansible.builtin.shell: |
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install containerd.io package
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Generate default containerd config
  ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1

- name: Modify containerd config for SystemdCgroup
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Enable containerd service on boot
  ansible.builtin.systemd:
    name: containerd
    enabled: yes

- name: gen the directory & add Kubernetes apt-key
  ansible.builtin.shell: >
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key |
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add Kubernetes APT repository
  ansible.builtin.shell: >
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' |
    tee /etc/apt/sources.list.d/kubernetes.list
    
- name: Update apt cache
  apt:
    update_cache: yes

- name: install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Mark Kubernetes pkg to hold version
  ansible.builtin.command:
    apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
