- name: Initialize Kubernetes Cluster
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ master_private_ip_addr | trim('\n') }}

- name: Set up kubeconfig for the user
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    dest: /tmp/calico.yaml

- name: Apply Calico network plugin
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml
  args:
    chdir: /tmp
