apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: ktb11chatbot/ktb-11-project-1-jenkins-image:v.0.0.4
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
            requests:
              memory: "500Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: kubectl-bin
              mountPath: /usr/bin/kubectl
            - name: containerd-bin
              mountPath: /usr/bin/containerd
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
        - name: kubectl-bin
          hostPath:
            path: /usr/bin/kubectl
            type: File
        - name: containerd-bin
          hostPath:
            path: /usr/bin/containerd
            type: File
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
