apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ktb-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ktb11chatbot/ktb-11-project-1-chatbot-fe:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              ephemeral-storage: "2Gi"
            limits:
              ephemeral-storage: "4Gi"