# This is init_pkg install playbook.yml file
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install vim # install vim
      ansible.builtin.apt:
        name:
          - vim
          - git
        state: present
