- name: Setup on master nodes
  hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Initialize Kubernetes Cluster
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=10.0.1.223

    - name: Set up kubeconfig for the user
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Calico Network Plugin
      ansible.builtin.shell: |
        kubectl apply -f https://calico-v3-25.netlify.app/archive/v3.25/manifests/calico.yaml >> pod_network_setup.txt

