- hosts: all
  become: yes
  vars_files:
    - secrets.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key_file }}"
  tasks:
    - name: Include install_pkg tasks
      include_tasks: roles/common/tasks/install_pkg.yml

    - name: Include install_kube_pkg tasks
      include_tasks: roles/kubernetes/tasks/install_kube_pkg.yml

    - name: Include config tasks
      include_tasks: roles/common/tasks/config.yml

- hosts: masters
  become: yes
  gather_facts: false
  vars_files:
    - secrets.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key_file }}"
  tasks:
    - name: Include master_config tasks
      include_tasks: roles/kubernetes/tasks/master_config.yml

    - name: Include worker_cfg tasks
      include_tasks: roles/kubernetes/tasks/worker_config.yml
