- name: Initialize Kubernetes master node
  hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout }} "

- name: Join worker nodes to the cluster
  hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - name: Join the cluster
      ansible.builtin.shell: "{{ join_command }} "

